apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo
data:
  NODE_ENV: "production"
  PORT: "5001"
  MONGO_URI_LOCAL: "mongodb://localhost:27017/todos"
  MONGO_URI_PROD: "mongodb://mongo:27017/todos"